# Generated by Django 3.2.6 on 2021-09-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(default='Hello, World!', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profimg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
