# Generated by Django 3.2.6 on 2021-09-02 04:15

from django.db import migrations, models
import ex01.models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0004_alter_user_profimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profimg',
            field=models.ImageField(blank=True, default=None, upload_to=ex01.models.User.path_file_name),
        ),
    ]
