# Generated by Django 3.2.6 on 2021-08-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0002_auto_20210818_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
    ]
