# Generated by Django 3.2.6 on 2021-08-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userfavouritearticle',
        ),
        migrations.CreateModel(
            name='UserFavouriteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex00.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex00.user')),
            ],
        ),
    ]
