# Generated by Django 3.2.6 on 2021-08-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('vote_tip', 'Can vote tip')]},
        ),
    ]
