# Generated by Django 3.2.6 on 2021-08-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_alter_tip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('downvote_tip', 'Can down vote tip')]},
        ),
    ]
